# Rename this file to languages.toml to enable multilingual support
[en]
label = "English"
direction = "ltr"
title = "Christian Martínez De La Rosa"
weight = 1

[es]
label = "Castellano"
direction = "ltr"
title = "Christian Martínez De La Rosa"
weight = 2

[ca]
label = "Català"
direction = "ltr"
title = "Christian Martínez De La Rosa"
weight = 3
